stages:
  - build

variables:
  VAULT_SERVER_URL: <VAULT_HCP_PUBLIC_URL>
  VAULT_NAMESPACE: admin
  VAULT_AUTH_ROLE: myproject-production
  VAULT_AUTH_PATH: jwt

build:
  image: hashicorp/vault:latest
  stage: build
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://gitlab.com
  secrets:
    DATABASE_PASSWORD:
      vault: production/db/password@ops  # translates to secret `ops/data/production/db`, field `password`
      file: false
      token: $VAULT_ID_TOKEN
  script:
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - echo "$VAULT_ID_TOKEN" | base64
    - echo "$VAULT_NAMESPACE"
    - echo "$VAULT_AUTH_ROLE"
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=$VAULT_AUTH_ROLE jwt=$VAULT_ID_TOKEN)"
    - vault token lookup
    - export PASSWORD="$(vault kv get -field=password ops/production/db)"
    - echo $PASSWORD
